### ISSUE TITLE
Xkey is not able to handle multiple message-header fields with the same field-name

### ISSUE THREAD

**Issue by hugocruz** [varnish/varnish-modules#102]
A backend sometimes transforms: 

```http
XKey: 1234 
XKey: 5678
```

into
```http
XKey: 1234,5678
```

From the [RFC 2616](https://tools.ietf.org/html/rfc2616#section-4.2) this should be allowed. 

> Multiple message-header fields with the same field-name MAY be
   present in a message if and only if the entire field-value for that
   header field is defined as a comma-separated list [i.e., #(values)].
   It MUST be possible to combine the multiple header fields into one
   "field-name: field-value" pair, without changing the semantics of the
   message, by appending each subsequent field-value to the first, each
   separated by a comma. The order in which header fields with the same
   field-name are received is therefore significant to the
   interpretation of the combined field value, and thus a proxy MUST NOT
   change the order of these field values when a message is forwarded.

Of course a VCL workaround can handle this, but shouldn't this be allowed by Xkey?

**Comment by tavisma** [comment]
would also like to see support for this, makes supporting both XKEY and Fast.ly Surrogate-Keys easier

**Comment by SpikesDivZero** [comment]
Hi @gquintard, I see this issue is currently assigned to you. Seeing as this issue's been open for a while now, would you mind if I put up a PR for review that I believe accomplishes this goal?

I do have some secondary concerns with regards to how this could be a breaking change (it's feasible that some users may be using comma as a key joiner), but I'm inclined to think that if properly documented or announced, this is an acceptable change in behavior to bring the VMOD closer to RFC specs.

**Comment by gquintard** [comment]
By all means, please propose a PR, this is not on my priority list right
now, but I will be glad to discuss it with you.

I'm not sure I see this as a breaking change, but let's worry about that
once we have some code
