### ISSUE TITLE
Varnish-modules wont build against varnish master.

### ISSUE THREAD

**Issue by simonvik** [varnish/varnish-modules#105]
bodyaccess depends on VRB_Iterate and 
xkey depends on OEV_*, ObjUnsubscribeEvents and multiple other functions.

Those functions and defines got moved to cache_varnishd.h in commit https://github.com/varnishcache/varnish-cache/commit/fee476acc085e6563225d35fd8e19f1b10f04139 and that file is not installed via the -dev package.

**Comment by nigoroll** [comment]
As I need the build to work _now_, I've just pushed a quick bandaid to  https://github.com/nigoroll/varnish-modules

**Comment by simonvik** [comment]
That solution works but its super-bad that it requires source tree.. 
If you go with this change then a src-pkg for deb, rpm is needed i think.

**Comment by Dridi** [comment]
This is on my plate for \_today\_.

**Comment by Dridi** [comment]
Since PHK wanted `cache_varnishd.h` to land in the "-dev" package or otherwise enforce building against a source tree, I double-checked and figured out we shouldn't need to build against a source tree.

See varnishcache/varnish-cache@90c4b747ced9053353c13d827ef0a0df5ab4445f

**Comment by simonvik** [comment]
Thanks! 
`Stuff that should *never* be exposed to a VMOD` from the cache_varnishd.h isnt so nice but thanks for solving the issue.

**Comment by Dridi** [comment]
At the same time giving access to the request body for example for security scanning was one of the goals of Varnish 4.0 and while it may not have materialized as a blessed VRT facility, `vmod-bodyaccess` was a first (out of tree) step in that direction.

Again, the introduction of a callback before objects leave storage was specifically added so that `vmod-xkey` could be open-sourced since its predecessor `vmod-hashtwo` would only work in Varnish Plus.

So yes, maybe `cache_varnishd.h` says this, but it also contradicts previous decisions so I wouldn't discard the possibility that maybe some of this history was forgotten when the decision was made to move things there and say those are no-no for VMODs.

I certainly hope this patch won't be reverted to bring us back to the Varnish 3 days.
