### ISSUE TITLE
Package varnishapi was not found in the pkg-config search path

### ISSUE THREAD

**Issue by jnthnclrk** [varnish/varnish-modules#139]
Trying to run ./bootstrap on Ubuntu 18, I get an error:

```
root@dst1:~/varnish-modules# ./bootstrap
Package varnishapi was not found in the pkg-config search path.
Perhaps you should add the directory containing `varnishapi.pc'
to the PKG_CONFIG_PATH environment variable
```

I have the following packages:

```
root@dst1:~/varnish-modules# dpkg -l | grep varnish
ii  libvarnishapi-dev               5.2.1-1                                     amd64        development files for Varnish
ii  libvarnishapi1                  5.2.1-1                                     amd64        shared libraries for Varnish
ii  varnish                         5.2.1-1                                     amd64        state of the art, high-performance web accelerator
```

And my Varnish is at 5.2.1:

```
root@dst1:~/varnish-modules# varnishd -V
varnishd (varnish-5.2.1 revision 67e562482)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2015 Varnish Software AS
```

Are there some more detailed installation instructions out there for Ubuntu?

Also, I couldn't find the file requested: 

```
root@dst1:~/varnish-modules# locate varnishapi.pc
root@dst1:~/varnish-modules#
```

**Comment by dmatetelki** [comment]
Hi @jnthnclrk,

Varnish-Software does not provide `varnish-cache 5.2.1` packages for `bionic`, only for `trusty`. Our packages are called: `varnish` and `varnish-dev` at https://packagecloud.io/varnishcache/varnish52/ (Your packages are from another vendor)

- I tried to build `Varnish-Cache` from source, branch `5.2` and `varnish-modules` went fine with it.
- Also with our `varnish-cache 5.2.1` packages from packagecloud it was ok.

Since I recommend you to install new `Varnish Cache` packages, take a look at the `6.0 Long Term Support` repo, which has packages for bionic:
https://packagecloud.io/varnishcache/varnish60lts


```
curl -s https://packagecloud.io/install/repositories/varnishcache/varnish60lts/script.deb.sh | sudo bash
sudo apt-get install varnish-dev=6.0.3-1~bionic
```

**Comment by jnthnclrk** [comment]
I think we have it working. Another developer helped me out. Judging by the history, I think he managed to get ./bootstrap and ./configure working with this repo.

**Comment by dmatetelki** [comment]
great!
