### ISSUE TITLE
Is gwist necessary?

### ISSUE THREAD

**Issue by gquintard** [varnish/varnish-modules#5]
On the heels of #4 , let's re-ignite an old fire: named vs gwist.

Both aim to offer dynamic backends based on ip/domain names. gwist was created after named to respond to a VHA need.

To keep things short:
- named is production-tested, and has some nice logging
- named has more options, but gwist is more straightforward (no vcl_init call)
- named support probing, gwist makes it easy to create throwaway backends
- named has RR, gwist just picks the first resolved backend
- named directors have a fixed port, so you may need to create multiple directors because your backends listen on :80, :8080 an 8888

We just had a discussion on IRC about it, but we didn't conclude it, so I'm writing here to keep track of the pros and cons. Do we really need gwist, and can't we beef up named to suit vha?

**Comment by rezan** [comment]
One thing I noticed in my testing is that gwist will block threads while the DNS resolution is happening. So if you have a backend which is DNS based and its on a 60s TTL, you will see little periods of no traffic every 60s when the backend expires and a new backend is being resolved. The second problem is that all requests during that 60s period goto 1 IP. So from this standpoint, I dont think gwist can be seriously used for a DNS backend. Its a good way to define an IP based backend or a simple DNS backend.

named does proper round robin across all the DNS entries and it will update the DNS entry without blocking during the resolution.

First, I think its best we merge these 2 solutions into 1 great solution:

* merge some of the simple usability features of gwist into named. If VHA needs the port to be defined on the request, I do not see why this cannot be done. I spent some time reviewing both and named has a better design and code structure, so its just a matter of hitting use case requirements.

Otherwise, the only way it maybe makes sense for Varnish to write 2 overlapping vmods is if 1 was a simple open source version and the other is a more advanced and complete VCP version. If not, its going to be very confusing for us to direct users (open source and paying) to the proper solution.

**Comment by Dridi** [comment]
> So from this standpoint, I dont think gwist can be seriously used for a DNS backend.

That's what Varnish 3 did, so I wouldn't worry too much about that.

> named does proper round robin across all the DNS entries and it will update the DNS entry without blocking during the resolution.

That's a choice I made, but there's always something to trade off. In this case, by using the blocking system's resolver I need one thread per domain per director.

**Comment by daghf** [comment]
Closing this. Follow-up discussion goes in #4

**Comment by huayra** [comment]
I believe that we have now landed this conversation as such:

- VMOD Gwist solves the problem of creating and defining an on-demand, cloud, goto, by-url-or-hostname backend.

- VMOD Named is more of a facility for backends that need DNS Dynamic resolving.

Gwist, now to become vmod-goto is now ready to enter varnish-modules as it brings no external dependencies with it.

Named should live its own life elsewhere for now.

So I am sort of re-opening this issue as " Consider adding ONDEMAND_CLOUD_GOTO_VMOD"
