### ISSUE TITLE
./configure --prefix=/usr/ sets installation dir to /usr/lib on 64bit platform.

### ISSUE THREAD

**Issue by PiotrCzapla** [varnish/varnish-modules#72]
Hi,
This seems to be super small issue whenever one run `./configure --prefix=/usr/` the modules will be installed to `/usr/lib` instead of `/usr/lib64`.
I'm not familiar with `autotools`  so I'm not sure how to fix it, or even if it is not an expected behaviour. Although the issue does not appear on any varnish library, so I've though you might be interested.

In the meantime I will just skip the `--prefix`.

**Comment by Dridi** [comment]
Try `rpm --eval %configure` to see how to correctly configure an autotools project for your system. I'm assuming you are running RHEL or CentOS by the look of your libdir.

This should be enough:

```
./configure --prefix=/usr --libdir=/usr/lib64
```

On Fedora 25 I can confirm that the `libdir` is correctly set if the prefix is `/usr`. Not sure about RHEL, and last time I checked on Ubuntu/Debian it is not the case.

Since Varnish 4.1.4-beta1 you should be able to inherit everything from Varnish's pkgconfig. However in an RPM spec you should use `%configure` instead of `./configure` and you shouldn't need to run the `bootstrap` script if you cared to pick the latest release archive from here:

https://download.varnish-software.com/varnish-modules/
